spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: password
      database: demo
      port: 27017
      host: localhost
server:
  servlet:
    context-path: /api/v1
# http://localhost:8080/swagger-ui/          --swagger url

# http://localhost:8080/api/v1/swagger-ui/    --swagger url with context path

